### ISSUE TITLE
How to configure FoxyProxy to connect to a network interface?

### ISSUE THREAD

**Issue by iTs-Mahdi-cyber** [foxyproxy/Foxyproxy_Chrome#1]
hi
I have two internet interfaces, `enp3s0f0` and `tun0`.
This is my `ip addr show ` output:
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

2: enp3s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 10:dd:b1:af:0d:8c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.113/24 brd 192.168.1.255 scope global dynamic noprefixroute enp3s0f0
       valid_lft 256979sec preferred_lft 256979sec
    inet6 fe80::1a75:249a:8c57:b6f1/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

7: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 10.18.0.39/16 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::e123:8c65:dba6:d5c5/64 scope link stable-privacy
       valid_lft forever preferred_lft forever`

The default interface is `enp4s0f0` but I want to use `tun0` in FoxyProxy.

Is there any way to do that?

EDIT1: I am sure that `tun0` has internet access. This is the proof:

`curl --interface tun0 http://ipecho.net/plain 

217.XX.XX.XX`

**Comment by ericjung** [comment]
This is not possible with FoxyProxy. The interfaces are not exposed by the browser.
