### ISSUE TITLE
Default pattern mode doesn't works with PAC

### ISSUE THREAD

**Issue by nE0sIghT** [foxyproxy/Foxyproxy_Chrome#3]
Hello.

I have default direct connection and proxy with PAC and patterns.  
I using PAC because I need to connect to secure https proxy and looks like there is no other option to use secure https proxy.  

In default pattern-matching mode I can not connect to websites that matches my PAC proxy patterns.  - the error is `ERR_TIMED_OUT`. 
However I can use PAC proxy when manually select it from FoxyProxy menu.

**Comment by ericjung** [comment]
You can implement the PAC rules as patterns in FoxyProxy. There's also the option for HTTPS proxy connections:

![image](https://user-images.githubusercontent.com/5875610/146658055-cd6c85a3-d5d5-4863-89da-976f62a59916.png)

**Comment by nE0sIghT** [comment]
Looks like your screenshot is from Firefox extension.  
Chrome extension was last released in 2015.

![image](https://user-images.githubusercontent.com/3389586/146665577-0f9e060f-f92e-40f5-bef2-eba06788246b.png)
