### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by erosman** [foxyproxy/Foxyproxy_Chrome#5]
Chrome has introduced manifest v3 which will come into force by Jan 2023. Firefox will be doing the same at a later date with some minor differences.

The future development of FoxyProxy extensions will be subject to MV3.

## Chrome
Similar to the current FoxyProxy extension
- **Implementation:**  via [proxy.PacScript](https://developer.chrome.com/docs/extensions/reference/proxy/#type-PacScript) (as PAC string)
- **Authentication:** Handled by the browser
   Not possible by the extension due to the removal of `'blocking'` in [webRequest.onAuthRequired](https://developer.chrome.com/docs/extensions/reference/webRequest/#event-onAuthRequired)
- **User Interface:** no UI for user/pass

### Option 1
Similar code-base as the Chrome extension
- **Implementation:** via [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) (as PAC string)
- **Authentication:** Handled by the browser
- **User Interface:** no UI for user/pass

### Option 2
- **Implementation:** via [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) (as PAC string)
- **Authentication:** via [webRequest.onAuthRequired](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired) for HTTP/HTTPS (not possible for SOCKS)
- **User Interface:** UI for user/pass

**Note:** Due to MV3 service worker limitations, option 2 will entail an async storage call on every `onAuthRequired` which will be fairly resource intensive.

### Option 3
Similar to the current FoxyProxy extension
- **Implementation:** via [proxy.onRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest)
- **Authentication:** via [proxy.onRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest)
- **User Interface:** UI for user/pass

**Note:** Due to MV3 service worker limitations, option 3 will entail an async storage call on every network connection which will be considerably resource intensive.

**Comment by ericjung** [comment]
Thanks for this excellent summary. Do any of the Firefox options allow for authentication with SOCKS?

**Comment by erosman** [comment]
> Do any of the Firefox options allow for authentication with SOCKS?

Option 3 is the only way to handle SOCKS authentication ATM.

Due to [Bug 122752](https://bugzilla.mozilla.org/show_bug.cgi?id=122752) (from 21 years ago) SOCKS authentication is not available directly in Firefox.
Chrome does not have the option. ([Issue 256785: SOCKS5 authentication support](https://bugs.chromium.org/p/chromium/issues/detail?id=256785))
Other browsers also do not appear to have SOCKS authentication feature.

**Comment by erosman** [comment]
Option 3 in MV3 would be like

```js
browser.proxy.onRequest.addListener(onRequest, {urls: ['<all_urls>']});

function onRequest(requestInfo) {
  /*   
    process
    ------------------
    1. get user preferences asynchronously e.g.
    await browser.storage.local.get();

    2. loop through all proxies
    3. convert all patterns to RegEx
    4. check if they match the criteria
    5. prepare a response with/without user/pass
    6. repeat the same for each network connection that can be 100s per tab
  */
}
```
