### ISSUE TITLE
Export doesn't work on Ubuntu

### ISSUE THREAD

**Issue by CodeSpartan** [foxyproxy/Foxyproxy_Chrome#6]
Foxyproxy Standard, Chrome, Ubuntu - export settings doesn't work: nothing happens when you hit the Export button.

**Comment by ericjung** [comment]
hi, this is a known problem and is being fixed in the next release (8.0) - code is [here](https://github.com/foxyproxy/browser-extension).

**Comment by ericjung** [comment]
Hello, for now you can export using [this method](https://help.getfoxyproxy.org/index.php/knowledge-base/export-foxyproxy-for-chrome-settings/).
